import 'dart:convert';
import 'package:flutter/foundation.dart';
import 'package:http/http.dart' as http;
import 'package:shared_preferences/shared_preferences.dart';
import '../models/hero_profile.dart';

class KnowledgeService {
  static const String _syncUrl =
      'https://raw.githubusercontent.com/Zcross091/frosty-wos-ai/main/heroes_data.json';
  static const String _cacheKey = 'frosty_cached_heroes_json';

  static List<HeroProfile> heroes = _buildDefaultHeroRoster();

  /// Synchronize Hero Codex with live website heroes_data.json on app startup
  static Future<void> syncWithWebsite() async {
    try {
      final prefs = await SharedPreferences.getInstance();

      // 1. Check offline cached JSON first
      final cachedJson = prefs.getString(_cacheKey);
      if (cachedJson != null && cachedJson.isNotEmpty) {
        _parseAndMergeJson(cachedJson);
      }

      // 2. Fetch latest online heroes_data.json from website repository
      final response = await http.get(Uri.parse(_syncUrl)).timeout(const Duration(seconds: 10));
      if (response.statusCode == 200) {
        final body = utf8.decode(response.bodyBytes);
        _parseAndMergeJson(body);
        await prefs.setString(_cacheKey, body);
        debugPrint('✅ KnowledgeService: Synced ${heroes.length} heroes from website JSON.');
      }
    } catch (e) {
      debugPrint('ℹ️ KnowledgeService sync notice: $e (using built-in offline master roster)');
    }
  }

  static void _parseAndMergeJson(String jsonStr) {
    try {
      final List<dynamic> data = jsonDecode(jsonStr);
      for (final item in data) {
        final int gen = item['gen'] ?? 0;
        final String label = item['label'] ?? 'Gen $gen';
        final String advice = item['advice'] ?? '';
        final String infName = item['infantry'] ?? '';
        final String lanName = item['lancer'] ?? '';
        final String marName = item['marksman'] ?? '';

        if (gen > 0) {
          // Infantry
          if (infName.isNotEmpty && !heroes.any((h) => h.name.toLowerCase() == infName.toLowerCase())) {
            heroes.insert(
              0,
              HeroProfile(
                name: infName,
                generation: gen,
                generationLabel: label,
                troopType: TroopType.infantry,
                rarity: gen >= 1 ? 'Mythic' : 'Epic',
                roleOverview: 'Frontline defensive anchor for $label. Absorb and mitigate high enemy rally assault.',
                attack: 2000 + gen * 1600,
                defense: 2500 + gen * 2100,
                health: 35000 + gen * 32000,
                expeditionMultiplier: 200.0 + gen * 120.0,
                explorationSkill: 'Glacial Bulwark: Shields frontline and enhances troop survivability.',
                expeditionSkill: 'Frontline Fortitude: Infantry Health and Defense +${20 + gen}%.',
                exclusiveGear: 'Titan Armor: Boosts defender lethality and reduces skill damage.',
                f2pAdvice: advice.isNotEmpty ? advice : 'Invest general shards to level to 4★.',
                bestTeam: '$infName (Lead) + $lanName + $marName',
              ),
            );
          }

          // Lancer
          if (lanName.isNotEmpty && !heroes.any((h) => h.name.toLowerCase() == lanName.toLowerCase())) {
            heroes.insert(
              0,
              HeroProfile(
                name: lanName,
                generation: gen,
                generationLabel: label,
                troopType: TroopType.lancer,
                rarity: gen >= 1 ? 'Mythic' : 'Epic',
                roleOverview: 'Mid-lane tactical cavalry for $label. Penetrate enemy marksman backlines.',
                attack: 2200 + gen * 1900,
                defense: 2200 + gen * 1900,
                health: 30000 + gen * 28000,
                expeditionMultiplier: 200.0 + gen * 120.0,
                explorationSkill: 'Lightning Strike: Rapid flurry striking multiple enemy targets.',
                expeditionSkill: 'Flank Mastery: Lancer Attack and Lethality +${20 + gen}%.',
                exclusiveGear: 'Spear of Valour: Increases critical strike chance and march speed.',
                f2pAdvice: advice.isNotEmpty ? advice : 'Great secondary investment for rally flanks.',
                bestTeam: '$infName + $lanName + $marName',
              ),
            );
          }

          // Marksman
          if (marName.isNotEmpty && !heroes.any((h) => h.name.toLowerCase() == marName.toLowerCase())) {
            heroes.insert(
              0,
              HeroProfile(
                name: marName,
                generation: gen,
                generationLabel: label,
                troopType: TroopType.marksman,
                rarity: gen >= 1 ? 'Mythic' : 'Epic',
                roleOverview: 'Backline siege damage carry for $label. Premier damage dealer for Bear Trap and PvP.',
                attack: 2600 + gen * 2200,
                defense: 1900 + gen * 1500,
                health: 26000 + gen * 23000,
                expeditionMultiplier: 200.0 + gen * 120.0,
                explorationSkill: 'Precision Shot: High-multiplier single-target sniper execution.',
                expeditionSkill: 'Siege Artillery: Marksman Attack +${25 + gen}%.',
                exclusiveGear: 'Storm Bow: Armor penetration and critical damage multiplier.',
                f2pAdvice: advice.isNotEmpty ? advice : 'Primary Lucky Wheel and shard investment target.',
                bestTeam: '$infName + $marName (DPS) + $lanName',
              ),
            );
          }
        }
      }
    } catch (e) {
      debugPrint('Error merging website heroes JSON: $e');
    }
  }

  static List<int> getAvailableGenerations() {
    final Set<int> gens = heroes.map((h) => h.generation).toSet();
    final List<int> sorted = gens.toList()..sort((a, b) => b.compareTo(a));
    return sorted;
  }

  static List<HeroProfile> getHeroesByGeneration(int gen) {
    return heroes.where((h) => h.generation == gen).toList();
  }

  static HeroProfile? getHeroByName(String name) {
    try {
      return heroes.firstWhere(
        (h) => h.name.toLowerCase() == name.toLowerCase(),
      );
    } catch (_) {
      return null;
    }
  }

  static List<HeroProfile> _buildDefaultHeroRoster() {
    return [
      // === Gen 16 ===
      HeroProfile(
        name: 'Seigel',
        generation: 16,
        generationLabel: 'Gen 16 (Legendary)',
        troopType: TroopType.infantry,
        rarity: 'Legendary',
        roleOverview: 'Ultra-tanky frontline reflect shield and Night\'s Guard veteran. Core anchor for Gen 16 PvP rallies.',
        attack: 28371,
        defense: 36984,
        health: 554778,
        expeditionMultiplier: 2131.70,
        explorationSkill: 'Spike Guard: Extends armor spikes 5s — Defense +25% and reflects 25% damage back to attackers.',
        expeditionSkill: 'Armor of Night: +25% Health for all troops. Night\'s Defense: reduces enemy Marksmen/Lancers Attack by 35%.',
        exclusiveGear: 'Blacklight Halberd: Heals 25% of reflected damage as Health. +15% defender Lethality.',
        f2pAdvice: 'F2P target 1-3★ on Lucky Wheel. P2W build to 4-6★ with exclusive gear for unstoppable rally defense.',
        bestTeam: 'Seigel (Lead) + Ursar + Aisling',
      ),
      HeroProfile(
        name: 'Aisling',
        generation: 16,
        generationLabel: 'Gen 16 (Legendary)',
        troopType: TroopType.marksman,
        rarity: 'Legendary',
        roleOverview: 'High-velocity siege sniper & endgame backline burst DPS. Highest marksman lethality in game history.',
        attack: 36984,
        defense: 28371,
        health: 369852,
        expeditionMultiplier: 2131.70,
        explorationSkill: 'Moonpiercer: Line AOE attack x380% with 60% armor penetration.',
        expeditionSkill: 'Lethal Focus: +30% Marksman Lethality and +25% Attack.',
        exclusiveGear: 'Silverwind Bow: Attacks ignore 35% target defense. Rally troops damage +20%.',
        f2pAdvice: 'The #1 damage carry for Gen 16. Max stars through Hall of Heroes and General Mythic shards.',
        bestTeam: 'Seigel + Aisling (DPS) + Ursar',
      ),
      HeroProfile(
        name: 'Ursar',
        generation: 16,
        generationLabel: 'Gen 16 (Legendary)',
        troopType: TroopType.lancer,
        rarity: 'Legendary',
        roleOverview: 'Windbreaker Support DPS & debuff specialist. Hall of Heroes exclusive with Marks of Valor.',
        attack: 36984,
        defense: 36984,
        health: 369852,
        expeditionMultiplier: 2131.70,
        explorationSkill: 'Toxic Gale: Spreads poison clouds causing continuous 60% DPS and -20% enemy movement speed.',
        expeditionSkill: 'Windbreaker: All troops Attack +25%. Decreases enemy frontline defense by 30%.',
        exclusiveGear: 'Gale Cleaver: Increases poison damage duration by 3s. +15% Lancer Lethality.',
        f2pAdvice: 'Acquire via weekly Hall of Heroes (Marks of Valor). Strong third pick for Gen 16 trio.',
        bestTeam: 'Seigel + Aisling + Ursar',
      ),

      // === Gen 15 ===
      HeroProfile(
        name: 'Hank',
        generation: 15,
        generationLabel: 'Gen 15 (Legendary)',
        troopType: TroopType.infantry,
        rarity: 'Legendary',
        roleOverview: 'Titan of the permafrost frontline. High health scaling and damage absorption.',
        attack: 24500,
        defense: 32000,
        health: 480000,
        expeditionMultiplier: 1850.00,
        explorationSkill: 'Glacial Rampart: Absorbs 40% incoming damage and pulses freeze waves.',
        expeditionSkill: 'Endless Bastion: Infantry Defense +35% and Health +30%.',
        exclusiveGear: 'Frostbound Shield: Gains +20% damage reduction when below 50% HP.',
        f2pAdvice: 'Primary Lucky Wheel investment for Gen 15 states (State 260–330).',
        bestTeam: 'Hank (Lead) + Viveca + Estrella',
      ),
      HeroProfile(
        name: 'Viveca',
        generation: 15,
        generationLabel: 'Gen 15 (Legendary)',
        troopType: TroopType.marksman,
        rarity: 'Legendary',
        roleOverview: 'Permafrost marksman with heavy armor destruction.',
        attack: 32000,
        defense: 24500,
        health: 320000,
        expeditionMultiplier: 1850.00,
        explorationSkill: 'Frost Arrow: Pierces 3 targets dealing 320% damage.',
        expeditionSkill: 'Frostbite: Reduces enemy squad Defense by 25%.',
        exclusiveGear: 'Icefall Bow: +20% damage to frozen targets.',
        f2pAdvice: 'Great Marksman carry for Bear Trap and SvS rally attacks.',
        bestTeam: 'Hank + Viveca + Estrella',
      ),
      HeroProfile(
        name: 'Estrella',
        generation: 15,
        generationLabel: 'Gen 15 (Legendary)',
        troopType: TroopType.lancer,
        rarity: 'Legendary',
        roleOverview: 'Starfall lancer cavalry with rapid critical strike triggers.',
        attack: 30000,
        defense: 28000,
        health: 330000,
        expeditionMultiplier: 1850.00,
        explorationSkill: 'Starfall Charge: Dashes through enemies with 250% burst damage.',
        expeditionSkill: 'Celestial Cavalry: Lancer Attack +30% and Lethality +25%.',
        exclusiveGear: 'Astral Lance: Extends cavalry speed and critical burst.',
        f2pAdvice: 'Strong flanking option in Gen 15 lineups.',
        bestTeam: 'Hank + Viveca + Estrella',
      ),

      // === Gen 14 ===
      HeroProfile(
        name: 'Elif',
        generation: 14,
        generationLabel: 'Gen 14 (Legendary)',
        troopType: TroopType.infantry,
        rarity: 'Legendary',
        roleOverview: 'Heavy fortress guardian with fortified shield barriers.',
        attack: 21000,
        defense: 28000,
        health: 410000,
        expeditionMultiplier: 1620.00,
        explorationSkill: 'Iron Barrier: Creates shield absorbing 30% damage.',
        expeditionSkill: 'Fortress Wall: Increases Infantry Defense by 30%.',
        exclusiveGear: 'Sentinel Aegis: Grants defense boost during Sunfire garrisons.',
        f2pAdvice: 'Reliable Gen 14 frontline wall.',
        bestTeam: 'Elif + Cara + Dominic',
      ),
      HeroProfile(
        name: 'Cara',
        generation: 14,
        generationLabel: 'Gen 14 (Legendary)',
        troopType: TroopType.marksman,
        rarity: 'Legendary',
        roleOverview: 'Top Lucky Wheel marksman carry for Gen 14.',
        attack: 28000,
        defense: 21000,
        health: 280000,
        expeditionMultiplier: 1620.00,
        explorationSkill: 'Rapid Blast: 3-round burst dealing 300% total damage.',
        expeditionSkill: 'Sniper Mastery: Marksman Attack +30% and Lethality +25%.',
        exclusiveGear: 'Precision Rifle: Critical hit rate +20%.',
        f2pAdvice: 'Must-build for F2P on Lucky Wheel in Gen 14 states.',
        bestTeam: 'Elif + Cara + Dominic',
      ),
      HeroProfile(
        name: 'Dominic',
        generation: 14,
        generationLabel: 'Gen 14 (Legendary)',
        troopType: TroopType.lancer,
        rarity: 'Legendary',
        roleOverview: 'Heavy lancer assault hero with high armor penetration.',
        attack: 26000,
        defense: 24000,
        health: 290000,
        expeditionMultiplier: 1620.00,
        explorationSkill: 'Thunder Charge: Deals 220% damage in area.',
        expeditionSkill: 'Thunderstrike: Lancer Attack +25%.',
        exclusiveGear: 'Thunder Spear: +15% damage against enemy backline.',
        f2pAdvice: 'Build through Hall of Heroes.',
        bestTeam: 'Elif + Cara + Dominic',
      ),

      // === Gen 13 ===
      HeroProfile(
        name: 'Gisela',
        generation: 13,
        generationLabel: 'Gen 13 (Legendary)',
        troopType: TroopType.infantry,
        rarity: 'Legendary',
        roleOverview: 'Premier Lucky Wheel tank for Gen 13 states.',
        attack: 18500,
        defense: 25000,
        health: 360000,
        expeditionMultiplier: 1420.00,
        explorationSkill: 'Aegis Pulse: Repels enemy frontlines and boosts defense.',
        expeditionSkill: 'Unyielding Defense: Infantry Health +30%.',
        exclusiveGear: 'Glacier Plate: Heals troops when taking burst damage.',
        f2pAdvice: 'Primary Lucky Wheel investment in Gen 13.',
        bestTeam: 'Gisela + Vulcanus + Flora',
      ),
      HeroProfile(
        name: 'Vulcanus',
        generation: 13,
        generationLabel: 'Gen 13 (Legendary)',
        troopType: TroopType.marksman,
        rarity: 'Legendary',
        roleOverview: 'Flame marksman with explosive burn DOT.',
        attack: 25000,
        defense: 18500,
        health: 250000,
        expeditionMultiplier: 1420.00,
        explorationSkill: 'Hellfire Barrage: Ignites ground dealing 280% damage.',
        expeditionSkill: 'Incinerate: Enemy squads suffer continuous burn damage.',
        exclusiveGear: 'Inferno Crossbow: Burn damage increased by 30%.',
        f2pAdvice: 'Top damage dealer for Bear Trap.',
        bestTeam: 'Gisela + Vulcanus + Flora',
      ),
      HeroProfile(
        name: 'Flora',
        generation: 13,
        generationLabel: 'Gen 13 (Legendary)',
        troopType: TroopType.lancer,
        rarity: 'Legendary',
        roleOverview: 'Support lancer with group attack boosts.',
        attack: 23000,
        defense: 21000,
        health: 260000,
        expeditionMultiplier: 1420.00,
        explorationSkill: 'Gale Sweep: Knocks back enemies dealing 200% damage.',
        expeditionSkill: 'Floral Gale: Increases all troops Attack by 20%.',
        exclusiveGear: 'Wind Staff: Rally speed and lancer lethality buff.',
        f2pAdvice: 'Acquire via Hall of Heroes.',
        bestTeam: 'Gisela + Vulcanus + Flora',
      ),

      // === Gen 12 ===
      HeroProfile(
        name: 'Hervor',
        generation: 12,
        generationLabel: 'Gen 12 (Legendary)',
        troopType: TroopType.infantry,
        rarity: 'Legendary',
        roleOverview: 'Viking shieldmaiden and heavy defense rally anchor.',
        attack: 16000,
        defense: 22000,
        health: 310000,
        expeditionMultiplier: 1240.00,
        explorationSkill: 'Valkyrie Shield: Absorbs 35% damage.',
        expeditionSkill: 'Shield Wall: Infantry Defense +25%.',
        exclusiveGear: 'Valkyrie Helm: Defender damage reduction.',
        f2pAdvice: 'Strong defensive anchor for SvS.',
        bestTeam: 'Hervor + Ligeia + Karol',
      ),
      HeroProfile(
        name: 'Ligeia',
        generation: 12,
        generationLabel: 'Gen 12 (Legendary)',
        troopType: TroopType.marksman,
        rarity: 'Legendary',
        roleOverview: 'Premier Lucky Wheel marksman carry for Gen 12.',
        attack: 22000,
        defense: 16000,
        health: 220000,
        expeditionMultiplier: 1240.00,
        explorationSkill: 'Sonic Arrow: Pierces multiple rows with 260% damage.',
        expeditionSkill: 'Precision Arrow: Marksman Lethality +25%.',
        exclusiveGear: 'Harmonic Bow: Critical strike boost.',
        f2pAdvice: 'Must-have Lucky Wheel marksman.',
        bestTeam: 'Hervor + Ligeia + Karol',
      ),
      HeroProfile(
        name: 'Karol',
        generation: 12,
        generationLabel: 'Gen 12 (Legendary)',
        troopType: TroopType.lancer,
        rarity: 'Legendary',
        roleOverview: 'Lancer striker with fast target switching.',
        attack: 20000,
        defense: 19000,
        health: 230000,
        expeditionMultiplier: 1240.00,
        explorationSkill: 'Lance Thrust: 210% damage single target.',
        expeditionSkill: 'Cavalry Assault: Lancer Attack +20%.',
        exclusiveGear: 'Honor Spear: Increases march lethality.',
        f2pAdvice: 'Hall of Heroes reward.',
        bestTeam: 'Hervor + Ligeia + Karol',
      ),

      // === Gen 11 ===
      HeroProfile(
        name: 'Eleonora',
        generation: 11,
        generationLabel: 'Gen 11 (Legendary)',
        troopType: TroopType.infantry,
        rarity: 'Legendary',
        roleOverview: 'Top Lucky Wheel tank for Gen 11 states.',
        attack: 14000,
        defense: 19500,
        health: 270000,
        expeditionMultiplier: 1080.00,
        explorationSkill: 'Frost Ward: Freezes nearby enemies for 1.5s.',
        expeditionSkill: 'Permafrost Shield: Infantry Health +25%.',
        exclusiveGear: 'Frost Core: Grants rally shield at combat start.',
        f2pAdvice: 'Primary Lucky Wheel investment in Gen 11.',
        bestTeam: 'Eleonora + Rufus + Lloyd',
      ),
      HeroProfile(
        name: 'Rufus',
        generation: 11,
        generationLabel: 'Gen 11 (Legendary)',
        troopType: TroopType.marksman,
        rarity: 'Legendary',
        roleOverview: 'Heavy armor-piercing sniper for Gen 11.',
        attack: 19500,
        defense: 14000,
        health: 195000,
        expeditionMultiplier: 1080.00,
        explorationSkill: 'Deadshot: Single shot dealing 320% damage.',
        expeditionSkill: 'Armor Breach: Reduces target defense by 20%.',
        exclusiveGear: 'Sniper Scope: Increases attack range and damage.',
        f2pAdvice: 'Build through Mythic shards.',
        bestTeam: 'Eleonora + Rufus + Lloyd',
      ),
      HeroProfile(
        name: 'Lloyd',
        generation: 11,
        generationLabel: 'Gen 11 (Legendary)',
        troopType: TroopType.lancer,
        rarity: 'Legendary',
        roleOverview: 'Aggressive lancer with high mobility.',
        attack: 18000,
        defense: 16500,
        health: 200000,
        expeditionMultiplier: 1080.00,
        explorationSkill: 'Rapid Lunge: Deals 190% damage.',
        expeditionSkill: 'Flank Charge: Lancer Lethality +20%.',
        exclusiveGear: 'Winged Lance: March speed +30%.',
        f2pAdvice: 'Hall of Heroes reward.',
        bestTeam: 'Eleonora + Rufus + Lloyd',
      ),

      // === Gen 10 ===
      HeroProfile(
        name: 'Gregory',
        generation: 10,
        generationLabel: 'Gen 10 (Mythic)',
        troopType: TroopType.infantry,
        rarity: 'Mythic',
        roleOverview: 'Frontline wall giving massive troop HP boosts.',
        attack: 12500,
        defense: 17000,
        health: 235000,
        expeditionMultiplier: 940.00,
        explorationSkill: 'Grand Guard: Shields allies for 20% health.',
        expeditionSkill: 'Iron Will: All troops Health +20%.',
        exclusiveGear: 'Guardian Plate: Reduces damage from marksmen.',
        f2pAdvice: 'Build for castle defense.',
        bestTeam: 'Gregory + Blanchette + Freya',
      ),
      HeroProfile(
        name: 'Blanchette',
        generation: 10,
        generationLabel: 'Gen 10 (Mythic)',
        troopType: TroopType.marksman,
        rarity: 'Mythic',
        roleOverview: 'Premier Lucky Wheel marksman carry in Gen 10.',
        attack: 17000,
        defense: 12500,
        health: 170000,
        expeditionMultiplier: 940.00,
        explorationSkill: 'Crystal Volley: 5 arrows dealing 250% damage.',
        expeditionSkill: 'Crystal Sharpness: Marksman Attack +25%.',
        exclusiveGear: 'Crystal Bow: Critical hit damage +25%.',
        f2pAdvice: 'Top Lucky Wheel target in Gen 10.',
        bestTeam: 'Gregory + Blanchette + Freya',
      ),
      HeroProfile(
        name: 'Freya',
        generation: 10,
        generationLabel: 'Gen 10 (Mythic)',
        troopType: TroopType.lancer,
        rarity: 'Mythic',
        roleOverview: 'Fast lancer with attack speed buffs.',
        attack: 15500,
        defense: 14500,
        health: 180000,
        expeditionMultiplier: 940.00,
        explorationSkill: 'Whirlwind Lance: 180% area damage.',
        expeditionSkill: 'Swift Assault: Lancer Attack +20%.',
        exclusiveGear: 'Wind Cleaver: Attack speed +15%.',
        f2pAdvice: 'Hall of Heroes reward.',
        bestTeam: 'Gregory + Blanchette + Freya',
      ),

      // === Gen 9 ===
      HeroProfile(
        name: 'Magnus',
        generation: 9,
        generationLabel: 'Gen 9 (Mythic)',
        troopType: TroopType.infantry,
        rarity: 'Mythic',
        roleOverview: 'Premier Lucky Wheel frontline wall for Gen 9.',
        attack: 11000,
        defense: 15000,
        health: 210000,
        expeditionMultiplier: 820.00,
        explorationSkill: 'Titan Guard: +25% defense for 5s.',
        expeditionSkill: 'Shield of Stone: Infantry Defense +25%.',
        exclusiveGear: 'Gargoyle Shield: Reflects 15% damage.',
        f2pAdvice: 'Top Lucky Wheel pick for Gen 9.',
        bestTeam: 'Magnus + Xura + Fred',
      ),
      HeroProfile(
        name: 'Xura',
        generation: 9,
        generationLabel: 'Gen 9 (Mythic)',
        troopType: TroopType.marksman,
        rarity: 'Mythic',
        roleOverview: 'High lethality marksman for Bear Trap and SvS.',
        attack: 15000,
        defense: 11000,
        health: 150000,
        expeditionMultiplier: 820.00,
        explorationSkill: 'Arrow Storm: Area damage 240%.',
        expeditionSkill: 'Keen Eye: Marksman Lethality +20%.',
        exclusiveGear: 'Falcon Bow: +15% damage to debuffed targets.',
        f2pAdvice: 'Great marksman carry.',
        bestTeam: 'Magnus + Xura + Fred',
      ),
      HeroProfile(
        name: 'Fred',
        generation: 9,
        generationLabel: 'Gen 9 (Mythic)',
        troopType: TroopType.lancer,
        rarity: 'Mythic',
        roleOverview: 'Lancer cavalry with armor-shredding charge.',
        attack: 13500,
        defense: 13000,
        health: 160000,
        expeditionMultiplier: 820.00,
        explorationSkill: 'Piercing Charge: 190% damage line.',
        expeditionSkill: 'Armor Shred: Reduces enemy frontline armor by 15%.',
        exclusiveGear: 'Iron Lance: +15% lancer attack.',
        f2pAdvice: 'Hall of Heroes reward.',
        bestTeam: 'Magnus + Xura + Fred',
      ),

      // === Gen 8 ===
      HeroProfile(
        name: 'Gatot',
        generation: 8,
        generationLabel: 'Gen 8 (Mythic)',
        troopType: TroopType.infantry,
        rarity: 'Mythic',
        roleOverview: 'Iron-boned warrior tank with immense rally defense resilience.',
        attack: 9800,
        defense: 13200,
        health: 185000,
        expeditionMultiplier: 720.00,
        explorationSkill: 'Iron Bones: Absorbs 30% damage.',
        expeditionSkill: 'Unbreakable: Infantry Health +20%.',
        exclusiveGear: 'Gauntlet of Might: Heals on taking heavy hits.',
        f2pAdvice: 'Strong SvS fortress defender.',
        bestTeam: 'Gatot + Hendrik + Sonya',
      ),
      HeroProfile(
        name: 'Hendrik',
        generation: 8,
        generationLabel: 'Gen 8 (Mythic)',
        troopType: TroopType.marksman,
        rarity: 'Mythic',
        roleOverview: 'Premier Lucky Wheel marksman sniper for Gen 8.',
        attack: 13200,
        defense: 9800,
        health: 132000,
        expeditionMultiplier: 720.00,
        explorationSkill: 'Precision Shell: 280% burst damage.',
        expeditionSkill: 'Marksman Focus: Marksman Attack +25%.',
        exclusiveGear: 'Hunting Rifle: +20% critical damage.',
        f2pAdvice: 'Primary Lucky Wheel investment in Gen 8.',
        bestTeam: 'Gatot + Hendrik + Sonya',
      ),
      HeroProfile(
        name: 'Sonya',
        generation: 8,
        generationLabel: 'Gen 8 (Mythic)',
        troopType: TroopType.lancer,
        rarity: 'Mythic',
        roleOverview: 'Lancer flanker with high combat speed.',
        attack: 12000,
        defense: 11500,
        health: 140000,
        expeditionMultiplier: 720.00,
        explorationSkill: 'Rapid Spear: 180% damage.',
        expeditionSkill: 'Flank Mastery: Lancer Lethality +15%.',
        exclusiveGear: 'Spear of Speed: March speed +25%.',
        f2pAdvice: 'Hall of Heroes reward.',
        bestTeam: 'Gatot + Hendrik + Sonya',
      ),

      // === Gen 7 ===
      HeroProfile(
        name: 'Edith',
        generation: 7,
        generationLabel: 'Gen 7 (Mythic)',
        troopType: TroopType.infantry,
        rarity: 'Mythic',
        roleOverview: 'Frontline Mech Tank & Damage Mitigation Specialist. Operates alongside her giant mech companion Mr. Tin.',
        attack: 8520,
        defense: 11100,
        health: 166500,
        expeditionMultiplier: 650.50,
        explorationSkill: 'Ironclad Punch: Mr. Tin strikes enemies in a fan area dealing 140% damage and stunning for 1s.',
        expeditionSkill: 'Strategic Balance: Reduces damage taken by friendly Marksmen by 20% and boosts Lancer damage by 20%.',
        exclusiveGear: 'Pocket Engineer: When Mr. Tin drops below 50% HP, restores 35% Max HP and grants +30% Defense.',
        f2pAdvice: 'Premier Gen 7 frontline tank for Sunfire Castle and SvS garrisons. Pair with Bradley + Gordon.',
        bestTeam: 'Edith (Lead) + Bradley + Gordon',
      ),
      HeroProfile(
        name: 'Bradley',
        generation: 7,
        generationLabel: 'Gen 7 (Mythic)',
        troopType: TroopType.marksman,
        rarity: 'Mythic',
        roleOverview: 'Heavy artillery marksman and long-range siege sniper. Top damage dealer in Gen 7.',
        attack: 11100,
        defense: 8520,
        health: 111000,
        expeditionMultiplier: 650.50,
        explorationSkill: 'Piercing Shell: Fires high-explosive round dealing 350% damage with armor penetration.',
        expeditionSkill: 'Artillery Precision: Marksman Attack +30% and Lethality +25%.',
        exclusiveGear: 'Bulwark Cannon: +20% Critical Hit damage against debuffed targets.',
        f2pAdvice: 'Top Lucky Wheel marksman carry for Gen 7. Build to 4★ for Bear Trap and SvS rallies.',
        bestTeam: 'Edith + Bradley + Gordon',
      ),
      HeroProfile(
        name: 'Gordon',
        generation: 7,
        generationLabel: 'Gen 7 (Mythic)',
        troopType: TroopType.lancer,
        rarity: 'Mythic',
        roleOverview: 'Cavalry flank specialist and damage amplifier.',
        attack: 9800,
        defense: 9800,
        health: 120000,
        expeditionMultiplier: 650.50,
        explorationSkill: 'Thunder Charge: Deals 190% damage.',
        expeditionSkill: 'Cavalry Focus: Lancer Attack +20%.',
        exclusiveGear: 'Storm Lance: Boosts friendly lancer damage.',
        f2pAdvice: 'Acquire through Hall of Heroes.',
        bestTeam: 'Edith + Bradley + Gordon',
      ),

      // === Gen 6 ===
      HeroProfile(
        name: 'Wayne',
        generation: 6,
        generationLabel: 'Gen 6 (Mythic)',
        troopType: TroopType.infantry,
        rarity: 'Mythic',
        roleOverview: 'Premier Lucky Wheel tank for Gen 6.',
        attack: 7400,
        defense: 9600,
        health: 145000,
        expeditionMultiplier: 580.00,
        explorationSkill: 'Steel Wall: Absorbs 25% damage.',
        expeditionSkill: 'Guardian Oath: Infantry Health +20%.',
        exclusiveGear: 'Titan Plate: Defense boost in garrisons.',
        f2pAdvice: 'Primary Lucky Wheel investment in Gen 6.',
        bestTeam: 'Wayne + Renee + Wu Ming',
      ),
      HeroProfile(
        name: 'Renee',
        generation: 6,
        generationLabel: 'Gen 6 (Mythic)',
        troopType: TroopType.marksman,
        rarity: 'Mythic',
        roleOverview: 'Backline marksman with high single-target burst.',
        attack: 9600,
        defense: 7400,
        health: 96000,
        expeditionMultiplier: 580.00,
        explorationSkill: 'Double Shot: 240% burst damage.',
        expeditionSkill: 'Sharpshooter: Marksman Attack +20%.',
        exclusiveGear: 'Eagle Bow: Critical hit boost.',
        f2pAdvice: 'Great damage dealer for Bear Trap.',
        bestTeam: 'Wayne + Renee + Wu Ming',
      ),
      HeroProfile(
        name: 'Wu Ming',
        generation: 6,
        generationLabel: 'Gen 6 (Mythic)',
        troopType: TroopType.lancer,
        rarity: 'Mythic',
        roleOverview: 'Martial lancer with rapid striking combos.',
        attack: 8500,
        defense: 8500,
        health: 105000,
        expeditionMultiplier: 580.00,
        explorationSkill: 'Dragon Strike: 170% damage.',
        expeditionSkill: 'Martial Spirit: Lancer Lethality +15%.',
        exclusiveGear: 'Dragon Spear: March speed buff.',
        f2pAdvice: 'Hall of Heroes reward.',
        bestTeam: 'Wayne + Renee + Wu Ming',
      ),

      // === Gen 5 ===
      HeroProfile(
        name: 'Hector',
        generation: 5,
        generationLabel: 'Gen 5 (Mythic)',
        troopType: TroopType.infantry,
        rarity: 'Mythic',
        roleOverview: 'Premier Lucky Wheel tank for Gen 5. Endurance wall built for long castle garrisons.',
        attack: 5800,
        defense: 7600,
        health: 114000,
        expeditionMultiplier: 520.00,
        explorationSkill: 'Indomitable: Gains +5% defense every 5s of battle up to +35%.',
        expeditionSkill: 'Castle Wall: Defender troops Health +30%.',
        exclusiveGear: 'Tower of Iron: Reduces incoming enemy skill damage by 20%.',
        f2pAdvice: 'Lucky Wheel target for Gen 5. Excellent frontline tank for SvS garrison defense.',
        bestTeam: 'Hector (Lead) + Gwen + Norah',
      ),
      HeroProfile(
        name: 'Gwen',
        generation: 5,
        generationLabel: 'Gen 5 (Mythic)',
        troopType: TroopType.marksman,
        rarity: 'Mythic',
        roleOverview: 'Top marksman sniper for Gen 5.',
        attack: 7600,
        defense: 5800,
        health: 76000,
        expeditionMultiplier: 520.00,
        explorationSkill: 'Power Shot: 220% damage with armor reduction.',
        expeditionSkill: 'Sniper Focus: Marksman Attack +20%.',
        exclusiveGear: 'Longbow: Critical rate boost.',
        f2pAdvice: 'Strong Marksman carry for Arena and Bear Trap.',
        bestTeam: 'Hector + Gwen + Norah',
      ),
      HeroProfile(
        name: 'Norah',
        generation: 5,
        generationLabel: 'Gen 5 (Mythic)',
        troopType: TroopType.lancer,
        rarity: 'Mythic',
        roleOverview: 'Lancer flanker with high combat lethality.',
        attack: 6800,
        defense: 6800,
        health: 85000,
        expeditionMultiplier: 520.00,
        explorationSkill: 'Swift Spear: 160% damage.',
        expeditionSkill: 'Cavalry Charge: Lancer Lethality +15%.',
        exclusiveGear: 'Silver Spear: Lancer attack buff.',
        f2pAdvice: 'Hall of Heroes reward.',
        bestTeam: 'Hector + Gwen + Norah',
      ),

      // === Gen 4 ===
      HeroProfile(
        name: 'Lynn',
        generation: 4,
        generationLabel: 'Gen 4 (Mythic)',
        troopType: TroopType.marksman,
        rarity: 'Mythic',
        roleOverview: 'Fast attack speed stun marksman. Top Lucky Wheel target in Gen 4.',
        attack: 5400,
        defense: 4100,
        health: 54000,
        expeditionMultiplier: 420.00,
        explorationSkill: 'Heavy Barrage: 3 rapid shots with 25% stun chance each.',
        expeditionSkill: 'Sharpshooter: Marksman Attack +30% and Lethality +20%.',
        exclusiveGear: 'Windforce: Increases attack speed by 25% in combat.',
        f2pAdvice: 'Must-build for F2P on Lucky Wheel. Excellent in Arena and Bear Trap.',
        bestTeam: 'Ahmose + Lynn + Reina',
      ),
      HeroProfile(
        name: 'Ahmose',
        generation: 4,
        generationLabel: 'Gen 4 (Mythic)',
        troopType: TroopType.infantry,
        rarity: 'Mythic',
        roleOverview: 'Egyptian pharaoh tank with reflective shields.',
        attack: 4100,
        defense: 5400,
        health: 82000,
        expeditionMultiplier: 420.00,
        explorationSkill: 'Pharaoh\'s Curse: Reflects 20% incoming damage.',
        expeditionSkill: 'Sand Barrier: Infantry Health +20%.',
        exclusiveGear: 'Ankh Shield: Restores HP on heavy hits.',
        f2pAdvice: 'Great tank for Gen 4 SvS defense.',
        bestTeam: 'Ahmose + Lynn + Reina',
      ),
      HeroProfile(
        name: 'Reina',
        generation: 4,
        generationLabel: 'Gen 4 (Mythic)',
        troopType: TroopType.lancer,
        rarity: 'Mythic',
        roleOverview: 'Lancer specialist with armor reduction debuffs.',
        attack: 4800,
        defense: 4800,
        health: 60000,
        expeditionMultiplier: 420.00,
        explorationSkill: 'Shadow Strike: 150% damage.',
        expeditionSkill: 'Weakpoint: Reduces target defense by 15%.',
        exclusiveGear: 'Shadow Blade: Lancer attack boost.',
        f2pAdvice: 'Hall of Heroes reward.',
        bestTeam: 'Ahmose + Lynn + Reina',
      ),

      // === Gen 3 ===
      HeroProfile(
        name: 'Mia',
        generation: 3,
        generationLabel: 'Gen 3 (Mythic)',
        troopType: TroopType.marksman,
        rarity: 'Mythic',
        roleOverview: 'Top Lucky Wheel marksman and essential damage multiplier for early Bear Trap.',
        attack: 3800,
        defense: 2900,
        health: 29000,
        expeditionMultiplier: 340.00,
        explorationSkill: 'Magic Arrow: Pierces enemies dealing 200% damage.',
        expeditionSkill: 'Frost Magic: Marksman Attack +20%.',
        exclusiveGear: 'Enchanted Bow: Critical rate +15%.',
        f2pAdvice: 'Must-spin Lucky Wheel hero for Gen 3 states.',
        bestTeam: 'Logan + Mia + Greg',
      ),
      HeroProfile(
        name: 'Logan',
        generation: 3,
        generationLabel: 'Gen 3 (Mythic)',
        troopType: TroopType.infantry,
        rarity: 'Mythic',
        roleOverview: 'Tough frontline tank with crowd control resistance.',
        attack: 2900,
        defense: 3800,
        health: 58000,
        expeditionMultiplier: 340.00,
        explorationSkill: 'Brawler: Stuns target for 1.5s.',
        expeditionSkill: 'Brawler Will: Infantry Defense +20%.',
        exclusiveGear: 'Heavy Knuckles: Increases defense in rallies.',
        f2pAdvice: 'Reliable Gen 3 frontline anchor.',
        bestTeam: 'Logan + Mia + Greg',
      ),
      HeroProfile(
        name: 'Greg',
        generation: 3,
        generationLabel: 'Gen 3 (Mythic)',
        troopType: TroopType.lancer,
        rarity: 'Mythic',
        roleOverview: 'Lancer cavalry with high single-target burst.',
        attack: 3400,
        defense: 3400,
        health: 42000,
        expeditionMultiplier: 340.00,
        explorationSkill: 'Power Lunge: 160% damage.',
        expeditionSkill: 'Cavalry Strike: Lancer Attack +15%.',
        exclusiveGear: 'Spiked Lance: Lancer lethality boost.',
        f2pAdvice: 'Acquire via Hall of Heroes.',
        bestTeam: 'Logan + Mia + Greg',
      ),

      // === Gen 2 ===
      HeroProfile(
        name: 'Flint',
        generation: 2,
        generationLabel: 'Gen 2 (Mythic)',
        troopType: TroopType.infantry,
        rarity: 'Mythic',
        roleOverview: 'The #1 must-have Lucky Wheel hero for all early states. Long-lasting F2P shield tank.',
        attack: 2400,
        defense: 3200,
        health: 48000,
        expeditionMultiplier: 280.00,
        explorationSkill: 'Molten Shield: Creates 35% HP absorption barrier and stuns frontline enemies for 1s.',
        expeditionSkill: 'Flame Armor: +25% Infantry Health and reduces enemy rally damage by 15%.',
        exclusiveGear: 'Forged Axe: Counter-attacks deal 20% bonus damage. +10% rally capacity.',
        f2pAdvice: 'Spend 100% of saved Lucky Wheel spins on Flint! Reach 4★ minimum.',
        bestTeam: 'Flint (Lead) + Alonso + Philly',
      ),
      HeroProfile(
        name: 'Alonso',
        generation: 2,
        generationLabel: 'Gen 2 (Mythic)',
        troopType: TroopType.marksman,
        rarity: 'Mythic',
        roleOverview: 'Exploration sniper and arena assassin with high critical strike rate.',
        attack: 3200,
        defense: 2400,
        health: 24000,
        expeditionMultiplier: 280.00,
        explorationSkill: 'Execution: Targets lowest HP enemy with 400% critical burst.',
        expeditionSkill: 'Eagle Eye: Marksman Lethality +20% and Attack +15%.',
        exclusiveGear: 'Hunting Rifle: +25% damage when enemy is below 50% HP.',
        f2pAdvice: 'Build through General Mythic Shards. Excellent in Exploration and Arena.',
        bestTeam: 'Flint + Alonso (DPS) + Philly',
      ),
      HeroProfile(
        name: 'Philly',
        generation: 2,
        generationLabel: 'Gen 2 (Mythic)',
        troopType: TroopType.lancer,
        rarity: 'Mythic',
        roleOverview: 'Support healer and debuff specialist.',
        attack: 2800,
        defense: 2800,
        health: 35000,
        expeditionMultiplier: 280.00,
        explorationSkill: 'Healing Light: Restores 25% HP to lowest ally.',
        expeditionSkill: 'Blessed March: All troops Defense +15%.',
        exclusiveGear: 'Medicine Kit: Enhances healing output.',
        f2pAdvice: 'Great support hero in Arena and rallies.',
        bestTeam: 'Flint + Alonso + Philly',
      ),

      // === Gen 1 ===
      HeroProfile(
        name: 'Jeronimo',
        generation: 1,
        generationLabel: 'Gen 1 (Mythic)',
        troopType: TroopType.infantry,
        rarity: 'Mythic',
        roleOverview: 'VIP Exclusive frontline warrior. Massive all-troop damage buff.',
        attack: 2100,
        defense: 2800,
        health: 42000,
        expeditionMultiplier: 220.00,
        explorationSkill: 'War Cry: Boosts all allies Attack by 25% for 6s.',
        expeditionSkill: 'Conqueror: All troops Attack +15% and Damage +10%.',
        exclusiveGear: 'Warlord Blade: Increases rally damage by 15%.',
        f2pAdvice: 'P2W VIP hero. F2P use Sergey or Flint instead.',
        bestTeam: 'Jeronimo + Molly + Natalia',
      ),
      HeroProfile(
        name: 'Molly',
        generation: 1,
        generationLabel: 'Gen 1 (Mythic)',
        troopType: TroopType.marksman,
        rarity: 'Mythic',
        roleOverview: 'Early game F2P marksman carry provided for free.',
        attack: 2800,
        defense: 2100,
        health: 21000,
        expeditionMultiplier: 220.00,
        explorationSkill: 'Snowball Strike: 180% area damage and 1.5s freeze.',
        expeditionSkill: 'Frost Shot: Marksman Attack +15%.',
        exclusiveGear: 'Snow Launcher: Increases snowball blast radius.',
        f2pAdvice: 'Great free early hero. Upgrade to 4★ for early arena.',
        bestTeam: 'Sergey + Molly + Jessie',
      ),
      HeroProfile(
        name: 'Natalia',
        generation: 1,
        generationLabel: 'Gen 1 (Mythic)',
        troopType: TroopType.lancer,
        rarity: 'Mythic',
        roleOverview: 'VIP First purchase lancer cavalry with beast companion.',
        attack: 2500,
        defense: 2500,
        health: 31000,
        expeditionMultiplier: 220.00,
        explorationSkill: 'Beast Pounce: 170% burst damage and stun.',
        expeditionSkill: 'Beast Roar: Lancer Attack +15%.',
        exclusiveGear: 'Claw Pendant: Critical rate +10%.',
        f2pAdvice: 'VIP/First purchase hero.',
        bestTeam: 'Jeronimo + Molly + Natalia',
      ),

      // === Gen 0 (Epic Core) ===
      HeroProfile(
        name: 'Jessie',
        generation: 0,
        generationLabel: 'Gen 0 (Epic Core)',
        troopType: TroopType.lancer,
        rarity: 'Epic',
        roleOverview: 'The single most important Rally Joiner in Whiteout Survival! 1st Skill boosts rally damage +25%.',
        attack: 1600,
        defense: 1600,
        health: 20000,
        expeditionMultiplier: 150.00,
        explorationSkill: 'Crossfire: Line AOE attack x150% damage.',
        expeditionSkill: 'Stand Fast: Increases total rally damage by 25% (Mandatory Bear Trap buff!).',
        exclusiveGear: 'Combat Uniform: Lancer Lethality +10%.',
        f2pAdvice: 'Max 1st Expedition skill immediately! Always send Jessie as 1st Hero in Bear Trap & SvS rallies.',
        bestTeam: 'Flint + Alonso + Jessie (Joiner)',
      ),
      HeroProfile(
        name: 'Sergey',
        generation: 0,
        generationLabel: 'Gen 0 (Epic Core)',
        troopType: TroopType.infantry,
        rarity: 'Epic',
        roleOverview: 'Top F2P defense wall. 1st Skill reduces damage taken by 20% in castle & fortress garrisons.',
        attack: 1300,
        defense: 1800,
        health: 28000,
        expeditionMultiplier: 150.00,
        explorationSkill: 'Rampart: Shields lowest ally for 20% HP.',
        expeditionSkill: 'Shielding: Reduces all damage taken by 20% for the entire garrison.',
        exclusiveGear: 'Heavy Shield: +15% defender defense.',
        f2pAdvice: 'Must-max for F2P. Place on wall for Sunfire Castle, SvS, and Crazy Joe defense.',
        bestTeam: 'Sergey (Lead) + Jessie + Bahiti',
      ),
      HeroProfile(
        name: 'Bahiti',
        generation: 0,
        generationLabel: 'Gen 0 (Epic Core)',
        troopType: TroopType.marksman,
        rarity: 'Epic',
        roleOverview: 'Reliable F2P sniper with high single-target critical damage in early Arena.',
        attack: 1800,
        defense: 1300,
        health: 13000,
        expeditionMultiplier: 150.00,
        explorationSkill: 'Sniper Shot: 300% single target burst.',
        expeditionSkill: 'Marksman Precision: Marksman Attack +15%.',
        exclusiveGear: 'Hunting Scope: Critical hit rate +10%.',
        f2pAdvice: 'Level up early for Arena and campaign until replaced by Flint/Alonso/Lynn.',
        bestTeam: 'Sergey + Bahiti + Jessie',
      ),
      HeroProfile(
        name: 'Seo-yoon',
        generation: 0,
        generationLabel: 'Gen 0 (Epic Core)',
        troopType: TroopType.lancer,
        rarity: 'Epic',
        roleOverview: 'Top Bear Trap joiner lead. Grants +20% Attack buff to the entire rally.',
        attack: 1500,
        defense: 1500,
        health: 18000,
        expeditionMultiplier: 150.00,
        explorationSkill: 'Healing Tune: Heals allies for 15% Max HP.',
        expeditionSkill: 'Inspire: Increases rally Attack by 20%.',
        exclusiveGear: 'Sound Amplifier: Increases rally buff duration.',
        f2pAdvice: 'Top 4 joiner lead for Bear Trap rallies alongside Jessie.',
        bestTeam: 'Flint + Mia + Seo-yoon',
      ),
      HeroProfile(
        name: 'Jasser',
        generation: 0,
        generationLabel: 'Gen 0 (Epic Core)',
        troopType: TroopType.marksman,
        rarity: 'Epic',
        roleOverview: 'Top Bear Trap rally joiner. Grants +20% Attack/Damage buff to rally.',
        attack: 1600,
        defense: 1400,
        health: 14000,
        expeditionMultiplier: 150.00,
        explorationSkill: 'Flame Arrow: Burns enemy row.',
        expeditionSkill: 'Tactical Fire: Increases rally damage output.',
        exclusiveGear: 'Combustion Core: Burn multiplier +10%.',
        f2pAdvice: 'Use as 3rd/4th joiner in Bear Trap rallies.',
        bestTeam: 'Flint + Lynn + Jasser',
      ),
      HeroProfile(
        name: 'Patrick',
        generation: 0,
        generationLabel: 'Gen 0 (Epic Core)',
        troopType: TroopType.infantry,
        rarity: 'Epic',
        roleOverview: 'Top defense garrison joiner. Grants +20% Health buff to defending troops.',
        attack: 1200,
        defense: 1700,
        health: 26000,
        expeditionMultiplier: 150.00,
        explorationSkill: 'Field Medic: Heals friendly frontline.',
        expeditionSkill: 'First Aid: +20% Health for all garrisoned troops.',
        exclusiveGear: 'Medical Bag: Defense boost.',
        f2pAdvice: 'Crucial for defending Sunfire Castle and SvS garrisons.',
        bestTeam: 'Sergey + Patrick + Jessie',
      ),
    ];
  }
}
