import '../models/hero_profile.dart';

class KnowledgeService {
  static final List<HeroProfile> heroes = [
    // --- Gen 16 ---
    HeroProfile(
      name: 'Seigel',
      generation: 16,
      generationLabel: 'Gen 16 (Legendary)',
      troopType: TroopType.infantry,
      rarity: 'Legendary',
      roleOverview: 'Ultra-tanky frontline reflect shield and Night\'s Guard veteran. Core anchor for Gen 16 PvP rallies.',
      attack: 28371,
      defense: 36984,
      health: 554778,
      expeditionMultiplier: 2131.70,
      explorationSkill: 'Spike Guard: Extends armor spikes 5s — Defense +25% and reflects 25% damage back to attackers.',
      expeditionSkill: 'Armor of Night: +25% Health for all troops. Night\'s Defense: reduces enemy Marksmen/Lancers Attack by 35%.',
      exclusiveGear: 'Blacklight Halberd: Heals 25% of reflected damage as Health. +15% defender Lethality.',
      f2pAdvice: 'F2P target 1-3★ on Lucky Wheel. P2W build to 4-6★ with exclusive gear for unstoppable rally defense.',
      bestTeam: 'Seigel (Lead) + Ursar + Aisling',
    ),
    HeroProfile(
      name: 'Aisling',
      generation: 16,
      generationLabel: 'Gen 16 (Legendary)',
      troopType: TroopType.marksman,
      rarity: 'Legendary',
      roleOverview: 'High-velocity siege sniper & endgame backline burst DPS. Highest marksman lethality in game history.',
      attack: 36984,
      defense: 28371,
      health: 369852,
      expeditionMultiplier: 2131.70,
      explorationSkill: 'Moonpiercer: Line AOE attack x380% with 60% armor penetration.',
      expeditionSkill: 'Lethal Focus: +30% Marksman Lethality and +25% Attack.',
      exclusiveGear: 'Silverwind Bow: Attacks ignore 35% target defense. Rally troops damage +20%.',
      f2pAdvice: 'The #1 damage carry for Gen 16. Max stars through Hall of Heroes and General Mythic shards.',
      bestTeam: 'Seigel + Aisling (DPS) + Ursar',
    ),
    HeroProfile(
      name: 'Ursar',
      generation: 16,
      generationLabel: 'Gen 16 (Legendary)',
      troopType: TroopType.lancer,
      rarity: 'Legendary',
      roleOverview: 'Windbreaker Support DPS & debuff specialist. Hall of Heroes exclusive with Marks of Valor.',
      attack: 36984,
      defense: 36984,
      health: 369852,
      expeditionMultiplier: 2131.70,
      explorationSkill: 'Toxic Gale: Spreads poison clouds causing continuous 60% DPS and -20% enemy movement speed.',
      expeditionSkill: 'Windbreaker: All troops Attack +25%. Decreases enemy frontline defense by 30%.',
      exclusiveGear: 'Gale Cleaver: Increases poison damage duration by 3s. +15% Lancer Lethality.',
      f2pAdvice: 'Acquire via weekly Hall of Heroes (Marks of Valor). Strong third pick for Gen 16 trio.',
      bestTeam: 'Seigel + Aisling + Ursar',
    ),

    // --- Gen 7 ---
    HeroProfile(
      name: 'Bradley',
      generation: 7,
      generationLabel: 'Gen 7 (Mythic)',
      troopType: TroopType.infantry,
      rarity: 'Mythic',
      roleOverview: 'Premier Gen 7 frontline defense anchor and stun tank.',
      attack: 8520,
      defense: 11100,
      health: 166500,
      expeditionMultiplier: 650.50,
      explorationSkill: 'Frost Barrier: Creates an energy shield absorbing 30% max HP damage and stuns attackers.',
      expeditionSkill: 'Iron Aegis: Garrison and rally troops Defense +30%.',
      exclusiveGear: 'Bulwark of the North: +15% Infantry Lethality and heals 10% HP every 8 turns.',
      f2pAdvice: 'Primary Gen 7 Lucky Wheel target. Highly durable tank for SvS and Castle battles.',
      bestTeam: 'Bradley (Lead) + Edith + Gordon',
    ),
    HeroProfile(
      name: 'Edith',
      generation: 7,
      generationLabel: 'Gen 7 (Mythic)',
      troopType: TroopType.marksman,
      rarity: 'Mythic',
      roleOverview: 'Armor-piercing marksman assassin designed to bypass enemy tanks and eliminate backline.',
      attack: 11100,
      defense: 8520,
      health: 111000,
      expeditionMultiplier: 650.50,
      explorationSkill: 'Piercing Bolt: Fires high-velocity shot that passes through frontline directly striking backline.',
      expeditionSkill: 'Sniper Focus: Marksman Lethality +35%.',
      exclusiveGear: 'Hawkeye Crossbow: +20% Critical Hit chance on debuffed targets.',
      f2pAdvice: 'Outstanding damage carry for Gen 7. Invest generic mythic shards after Bradley reaches 3★.',
      bestTeam: 'Bradley + Edith + Gordon',
    ),

    // --- Gen 4 ---
    HeroProfile(
      name: 'Lynn',
      generation: 4,
      generationLabel: 'Gen 4 (Mythic)',
      troopType: TroopType.marksman,
      rarity: 'Mythic',
      roleOverview: 'Fast attack speed stun marksman. Top Lucky Wheel target in Gen 4.',
      attack: 5400,
      defense: 4100,
      health: 54000,
      expeditionMultiplier: 420.00,
      explorationSkill: 'Heavy Barrage: 3 rapid shots with 25% stun chance each.',
      expeditionSkill: 'Sharpshooter: Marksman Attack +30% and Lethality +20%.',
      exclusiveGear: 'Windforce: Increases attack speed by 25% in combat.',
      f2pAdvice: 'Must-build for F2P on Lucky Wheel. Excellent in Arena and Bear Trap.',
      bestTeam: 'Hector + Lynn + Ahmose',
    ),
    HeroProfile(
      name: 'Hector',
      generation: 4,
      generationLabel: 'Gen 4 (Mythic)',
      troopType: TroopType.infantry,
      rarity: 'Mythic',
      roleOverview: 'Endurance wall built for long castle garrisons and sustained rallies.',
      attack: 4100,
      defense: 5400,
      health: 81000,
      expeditionMultiplier: 420.00,
      explorationSkill: 'Indomitable: Gains +5% defense every 5s of battle up to +35%.',
      expeditionSkill: 'Castle Wall: Defender troops Health +30%.',
      exclusiveGear: 'Tower of Iron: Reduces incoming enemy skill damage by 20%.',
      f2pAdvice: 'King of Icefield reward. Build after Lynn for SvS garrison defense.',
      bestTeam: 'Hector + Lynn + Ahmose',
    ),

    // --- Gen 2 ---
    HeroProfile(
      name: 'Flint',
      generation: 2,
      generationLabel: 'Gen 2 (Mythic)',
      troopType: TroopType.infantry,
      rarity: 'Mythic',
      roleOverview: 'Frontline burn tank with Dragonbane flamethrower. #1 F2P Lucky Wheel target.',
      attack: 2043,
      defense: 2664,
      health: 39960,
      expeditionMultiplier: 240.19,
      explorationSkill: 'Fires of Vengeance: AOE flame attack and target takes +30% damage. Incinerator heals 40% HP.',
      expeditionSkill: 'Pyromaniac: Rally troops 20% chance to burn. Burning Resolve: Attack +25%.',
      exclusiveGear: 'Dragonbane: After Incinerator, +24% Attack. Garrison defender troops Attack +15%.',
      f2pAdvice: 'Absolute essential for F2P players in Gen 2. Reach 3-4★ on Lucky Wheel before saving for Gen 3.',
      bestTeam: 'Flint (Lead) + Alonso + Philly',
    ),
    HeroProfile(
      name: 'Alonso',
      generation: 2,
      generationLabel: 'Gen 2 (Mythic)',
      troopType: TroopType.marksman,
      rarity: 'Mythic',
      roleOverview: 'Ranged DPS with teamwide stun trapnet and damage amplification.',
      attack: 3235,
      defense: 2220,
      health: 19980,
      expeditionMultiplier: 240.19,
      explorationSkill: 'Trapnet: AOE Attack x280% + 1.5s stun. Tidal Force: AOE Attack x70%.',
      expeditionSkill: 'Onslaught: 20% chance enemy stun 1 turn. Poison Harpoon: +50% damage.',
      exclusiveGear: 'Captain Ahab: Heals weakest ally 15% HP on hit. Rally Lethality +15%.',
      f2pAdvice: 'Second Gen 2 target after Flint. Extremely high exploration attack.',
      bestTeam: 'Flint + Alonso + Philly',
    ),
    HeroProfile(
      name: 'Philly',
      generation: 2,
      generationLabel: 'Gen 2 (Mythic)',
      troopType: TroopType.lancer,
      rarity: 'Mythic',
      roleOverview: 'First major healer and poison support for prolonged SvS rallies.',
      attack: 2664,
      defense: 2220,
      health: 26640,
      expeditionMultiplier: 240.20,
      explorationSkill: 'First Aid: Heals all allies Attack x280%. Paralytic Lotion: 1s disable.',
      expeditionSkill: 'Miracle Herb: Every 12 turns, heals troops 15% HP.',
      exclusiveGear: 'Pharmacologica: Herbal heals +70% effectiveness. Garrison Health +15%.',
      f2pAdvice: 'Third priority for F2P. Shines in prolonged SvS and Bear Trap.',
      bestTeam: 'Flint + Alonso + Philly',
    ),

    // --- Gen 1 ---
    HeroProfile(
      name: 'Jeronimo',
      generation: 1,
      generationLabel: 'Gen 1 (Mythic)',
      troopType: TroopType.infantry,
      rarity: 'Mythic',
      roleOverview: 'VIP rally leader and universal top-tier joiner buff.',
      attack: 1620,
      defense: 1620,
      health: 24300,
      expeditionMultiplier: 150.00,
      explorationSkill: 'Warlord\'s Slash: Cleave attack dealing 260% damage.',
      expeditionSkill: 'Warlord\'s Might: +15% Damage Dealt to rally (Top joiner buff).',
      exclusiveGear: 'Greatsword of Dominance: Rally troops Attack +15%.',
      f2pAdvice: 'VIP exclusive. If unlocked, use as universal rally joiner lead.',
      bestTeam: 'Jeronimo + Natalia + Molly',
    ),
    HeroProfile(
      name: 'Molly',
      generation: 1,
      generationLabel: 'Gen 1 (Mythic)',
      troopType: TroopType.marksman,
      rarity: 'Mythic',
      roleOverview: 'Day 1 free mythic damage dealer and arena snowball stunner.',
      attack: 1800,
      defense: 1350,
      health: 13500,
      expeditionMultiplier: 150.00,
      explorationSkill: 'Snowball Barrage: Stuns 2 enemies for 1.5s and deals AOE splash damage.',
      expeditionSkill: 'Winter Call: Marksman Attack +25%.',
      exclusiveGear: 'Snowy Mittens: Marksman Lethality +15%.',
      f2pAdvice: 'Max out immediately through Exploration and Hero Hall. F2P core until Gen 2.',
      bestTeam: 'Sergey + Molly + Bahiti',
    ),

    // --- Epic Core (Gen 0) ---
    HeroProfile(
      name: 'Jessie',
      generation: 0,
      generationLabel: 'Epic Core (F2P)',
      troopType: TroopType.lancer,
      rarity: 'Epic',
      roleOverview: 'THE #1 RALLY JOINER IN WHITEOUT SURVIVAL. +25% Damage Dealt to entire rally.',
      attack: 900,
      defense: 900,
      health: 9000,
      expeditionMultiplier: 80.00,
      explorationSkill: 'Tactical Grenade: Stuns front enemy and deals 200% burst damage.',
      expeditionSkill: 'Inspire (Top-Right): ALL RALLY TROOPS GAIN +25% DAMAGE DEALT.',
      exclusiveGear: 'Combat Radio: March speed +20%.',
      f2pAdvice: 'ALWAYS send Jessie as your 1st hero when joining alliance Bear Trap & SvS rallies!',
      bestTeam: 'Jessie (Joiner Lead) + Sergey + Bahiti',
    ),
    HeroProfile(
      name: 'Sergey',
      generation: 0,
      generationLabel: 'Epic Core (F2P)',
      troopType: TroopType.infantry,
      rarity: 'Epic',
      roleOverview: 'Best early-game F2P defense shield. -20% incoming damage taken.',
      attack: 750,
      defense: 1200,
      health: 15000,
      expeditionMultiplier: 80.00,
      explorationSkill: 'Heavy Shield: Creates 35% HP shield for 5s.',
      expeditionSkill: 'Iron Defense: All troops take -20% damage in battle.',
      exclusiveGear: 'Steel Aegis: Defense +15%.',
      f2pAdvice: 'Primary tank for all early game exploration and city defense until Flint/Bradley.',
      bestTeam: 'Sergey + Jessie + Molly',
    ),
    HeroProfile(
      name: 'Seo-yoon',
      generation: 0,
      generationLabel: 'Epic Core (F2P)',
      troopType: TroopType.lancer,
      rarity: 'Epic',
      roleOverview: 'Essential Top-4 Rally Joiner. Provides +20% Attack buff to entire alliance rally.',
      attack: 950,
      defense: 850,
      health: 9500,
      expeditionMultiplier: 80.00,
      explorationSkill: 'Song of Courage: Heals lowest ally 180% and increases attack speed.',
      expeditionSkill: 'War Hymn (Top-Right): Entire rally march gains +20% Attack.',
      exclusiveGear: 'Microphone of Valor: Healing efficiency +25%.',
      f2pAdvice: 'Must-have joiner for Bear Trap when Jessie is already sent in march 1.',
      bestTeam: 'Seo-yoon (Joiner 2) + Patrick + Gina',
    ),
  ];

  static List<HeroProfile> getHeroesByGeneration(int gen) {
    return heroes.where((h) => h.generation == gen).toList();
  }

  static HeroProfile? getHeroByName(String name) {
    try {
      return heroes.firstWhere(
        (h) => h.name.toLowerCase() == name.toLowerCase().trim(),
      );
    } catch (_) {
      return null;
    }
  }
}
